// Reflections Array
export const reflections = [
    "Something feels off. Why am I doing this?",
    "This feels wrong. But I have to keep trying, right?",
    "Should I keep going? There has to be a better way.",
    "She doesn’t deserve this. No one does. I should stop… but what if the next time is different?",
    "This isn’t me. I just need to find the right approach. That’s all.",
    "Why isn’t this working? I’ve done everything right!",
    "Maybe… maybe I’m not the problem here. Maybe she’s the one who doesn’t see what we could be.",
    "How can I do such a thing? Am I turning into one of those guys?",
    "I hate this. I hate the way I feel, but I can’t stop. What’s wrong with me?",
    "It’s not supposed to be like this. Why can’t I just get it right? Why can’t she see me?",
    "What if I’m making it worse? What if every time I reset, I lose another piece of myself?",
    "This isn’t about her anymore, is it? It’s about proving that I can do it.",
    "I don’t want to hurt her, but I’m running out of options. I’ll just try one more time.",
    "She’s laughing again… like I’m a joke. Is that what I am now? A joke?",
    "I hate myself for doing this. But what else can I do? Walk away?",
    "I should let her go. I should. But I’m too deep in this now.",
    "Every time I try, I lose a little more of her. Of me. Why am I still pushing?",
    "I’m better than this. I deserve more than this humiliation.",
    "Maybe she wants me to fail. Maybe she gets some sick pleasure out of it.",
    "How many times do I have to do this before she finally understands? We’re meant to be together.",
    "This fucking girl. Why doesn’t she get it? I’m the one who’s right for her!",
    "It’s like she’s trying to make me fail. Maybe she likes seeing me suffer.",
    "I’ve come too far to give up now. I’m not the one who’s wrong here.",
    "This is all just a game to her, isn’t it? Well, I can play games too.",
    "She’s just another obstacle. I’ll get past her like I’ve done before.",
    "Maybe if she knew what I’ve been through, she’d stop playing hard to get.",
    "I fucking hate this. But I hate losing more. I can’t lose again.",
    "Why can’t she see that I’m the one she needs? I’m the one who’s been here, trying again and again.",
    "Am I going crazy? Or is it her? Maybe it’s both of us.",
    "This isn’t about love anymore. It’s about winning.",
    "She owes me this. After everything I’ve done… everything I’ve tried.",
    "I didn’t come this far just to walk away empty-handed.",
    "I hate her. I hate what she’s turned me into. But I can’t stop. I won’t stop.",
    "She has no idea what I’m capable of. I’ll show her.",
    "I could break her if I wanted to. She wouldn’t stand a chance.",
    "She thinks she can just walk away from me? Not this time.",
    "I’ll fucking tear down her whole world if she keeps this up.",
    "She’s mine. She just doesn’t know it yet.",
    "One way or another, I’ll get what I deserve. She can’t hide from me.",
    "I’ll make her beg for me. She’ll wish she’d given in sooner.",
    "She’s a fucking puppet. And I’m the one pulling the strings.",
    "I’ll crush her resistance. She’ll have no choice but to fall for me.",
    "I want to see her break. I want her to know she lost.",
    "I could ruin her in an instant. It would be so easy.",
    "If she keeps pushing me, I won’t be responsible for what happens.",
    "She’s pushing me to the edge. And when I snap, she’ll regret it.",
    "I could hurt her. I want to hurt her. And I don’t care anymore.",
    "Why should I be the one who’s suffering? It’s her turn to feel the pain.",
    "She’ll wish she’d never met me. By the time I’m done, she’ll regret everything.",
    "I’ll fucking destroy everything she cares about if that’s what it takes.",
    "There’s a part of me that wants to make her pay. And I’m so close to letting it loose.",
    "What’s stopping me from making her suffer? Nothing. Nothing.",
    "She can run, but she can’t escape me. I’ll always be right behind her.",
    "I don’t care if she screams. It’s music to my ears.",
    "She’s not just a girl anymore. She’s my possession.",
    "Why does this hurt so much? I just want her to see me the way I see her.",
    "I’m not giving up. Not now. Not ever. We’re supposed to be together.",
    "I’ve lost track of how many times I’ve done this. But every time, I get a little closer.",
    "She doesn’t have a choice anymore. I’ll make her see.",
    "Maybe this isn’t love. Maybe this is something darker… but it doesn’t matter anymore.",
    "I hate myself for what I’ve become. But I can’t go back. Not after all of this.",
    "What am I doing? What have I done? Is this even about her anymore?",
    "I’m stuck in this loop. But the worst part? I don’t want it to end.",
    "She doesn’t know how lucky she is to have me trying this hard.",
    "I’ll make her love me. Even if it kills me.",
    "This isn’t who I wanted to be. But it’s who I am now.",
    "I’m starting to think I don’t deserve her. But she sure as hell doesn’t deserve me.",
    "There’s no turning back. I’m too far gone now.",
    "She’ll see. One way or another, she’ll have to see.",
    "I should’ve given up a long time ago. But giving up? That’s for losers.",
    "Maybe I’ll never get it right. But I’d rather die trying than walk away.",
    "It doesn’t matter what it takes anymore. I’ll do whatever I have to.",
];

// Dynamic Reflection State Generator
export function getReflectionState(reflectionIndex) {
    const reflectionText = reflections[reflectionIndex % reflections.length];
    return [
        reflectionText, 
        [],
        "Press ENTER! You will do it!" // Placeholder for reflection
    ];
}

